Update rundashboard

diff --git a/rundashboard b/rundashboard
--- a/rundashboard
+++ b/rundashboard
@@ -22,6 +22,7 @@ NC='\033[0m' # No Color
 
 # Clear the screen
 clear
+
 # Check if the script is run as root
 if [ "$EUID" -ne 0 ]; then
   echo -e "${RED}Please run this script as root.${NC}"
@@ -30,44 +31,31 @@ fi
 
 echo -e "${CYAN}$ascii_art${NC}"
 
-
 echo "* Installing Dependencies"
 
 # Update package list and install dependencies
 sudo apt update
-sudo apt install -y curl software-properties-common
+sudo apt install -y curl software-properties-common git
 curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
-sudo apt-get install nodejs -y 
-sudo apt install git -y
+sudo apt-get install -y nodejs 
 
-echo_message "* Installed Dependencies"
+echo "* Dependencies Installed"
 
-echo_message "* Installing Files"
+echo "* Cloning Repository"
 
-# Create directory, clone repository, and install files
-mkdir -p Oversee
-cd Oversee || { echo_message "Failed to change directory to skyport"; exit 1; }
+# Clone repository
 git clone https://github.com/jhondrheydacudao/Hosting.git
-cd Oversee || { echo_message "Failed to change directory to panel"; exit 1; }
+cd Hosting || { echo "Failed to change directory to Hosting"; exit 1; }
+
+echo "* Installing NPM Packages"
 npm install
 
-echo_message "* Installed Files"
+echo "* Starting Server with PM2"
 
-echo_message "* Starting Skyport"
-
-# Run setup scripts
-npm run seed
-npm run createUser
-
-echo "* Starting Skyport With PM2"
-
-# Install panel and start the application
+# Install PM2 and start the application
 sudo npm install -g pm2
-pm2 start index.js
+pm2 start index.js --name Hosting
+pm2 save
 
-echo "* Skyport Installed and Started on Port 3001"
-
-
-# Clear the screen after finishing
-clear
-echo "Made by Jishnu"
+echo "* Installation Complete!"
+echo "* Hosting Panel is running on Port 3001"
